### PR TITLE
save_tokens fix error in case origin arg is not set

### PR DESCRIPTION
**Pull request by csandker**
Some commands/modules might not set the `origin` argument introduced in #99. This could cause the following error.

```
Traceback (most recent call last):
  File "/home/csandker/01-tools/ROADtools/venv/bin/roadtx", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/csandker/01-tools/ROADtools/venv/lib/python3.12/site-packages/roadtools/roadtx/main.py", line 1054, in main
    auth.save_tokens(args)
  File "/home/csandker/01-tools/ROADtools/venv/lib/python3.12/site-packages/roadtools/roadlib/auth.py", line 1582, in save_tokens
    if args.origin:
       ^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'origin'
```

Fixed by checking if attribute is set on the `args` object.

### CODE REVIEW

**Comment by dirkjanm** [comment]
I still have to review the origin logic, but I wonder if setting this from `self.origin` instead of from `args.origin`, which may not always exist, wouldn't be a cleaner fix here.

**Comment by csandker** [comment]
ah good call... I can check that next week. If you're quicker and figure it works with `self.origin` feel free to push and drop this MR ;)

**Comment by dirkjanm** [comment]
closing since I fixed this as suggested above, since this is more consistent with library usage of the class
